=== JoLuMTavares/Videothek/genre_schau/genre_schau.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="resultset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="row" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="row">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="id"/>
								<xs:enumeration value="titel"/>
								<xs:enumeration value="jahr"/>
								<xs:enumeration value="laenge"/>
								<xs:enumeration value="genres"/>
								<xs:enumeration value="regisseure"/>
								<xs:enumeration value="schauspieler"/>
								<xs:enumeration value="plot"/>
								<xs:enumeration value="sprache"/>
								<xs:enumeration value="laender"/>
								<xs:enumeration value="plakat_url|"/>
								<xs:enumeration value="imdbID"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JoLuMTavares/Videothek/genre_schau/kevins2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="genre_schau.xslt"?>
<resultset statement="SELECT * FROM filmen WHERE genres LIKE '%Drama%' AND schauspieler LIKE '%Kevin Spacey%' AND jahr &gt; 1990 AND jahr &lt; 2000
" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="genre_schau.xsd">
  <row>
	<field name="id">18</field>
	<field name="titel">Se7en</field>
	<field name="jahr">1995</field>
	<field name="laenge">127 min</field>
	<field name="genres">&quot;Crime;Drama;Mystery&quot;</field>
	<field name="regisseure">&quot;David Fincher&quot;</field>
	<field name="schauspieler">&quot;Andrew Kevin Walker;Daniel Zacapa;Kevin Spacey;Morgan Freeman&quot;</field>
	<field name="plot">&quot;Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.&quot;</field>
	<field name="sprache">&quot;English&quot;</field>
	<field name="laender">&quot;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg</field>
	<field name="imdbID">tt0114369</field>
  </row>

  <row>
	<field name="id">54</field>
	<field name="titel">American Beauty</field>
	<field name="jahr">1999</field>
	<field name="laenge">122 min</field>
	<field name="genres">&quot;Drama;Romance&quot;</field>
	<field name="regisseure">&quot;Sam Mendes&quot;</field>
	<field name="schauspieler">&quot;Annette Bening;Kevin Spacey;Thora Birch;Wes Bentley&quot;</field>
	<field name="plot">&quot;A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.&quot;</field>
	<field name="sprache">&quot;English&quot;</field>
	<field name="laender">&quot;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BMjM4NTI5NzYyNV5BMl5BanBnXkFtZTgwNTkxNTYxMTE@._V1_SX300.jpg</field>
	<field name="imdbID">tt0169547</field>
  </row>

  <row>
	<field name="id">83</field>
	<field name="titel">L.A. Confidential</field>
	<field name="jahr">1997</field>
	<field name="laenge">138 min</field>
	<field name="genres">&quot;Crime;Drama;Mystery&quot;</field>
	<field name="regisseure">&quot;Curtis Hanson&quot;</field>
	<field name="schauspieler">&quot;Guy Pearce;James Cromwell;Kevin Spacey;Russell Crowe&quot;</field>
	<field name="plot">&quot;As corruption grows in 1950s LA, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.&quot;</field>
	<field name="sprache">&quot;English&quot;</field>
	<field name="laender">&quot;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BMDBlYzAwZDktNzM2MS00YzBlLWI4ODQtZTlkNmMxZDc3NGRkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg</field>
	<field name="imdbID">tt0119488</field>
  </row>
</resultset>

=== JoLuMTavares/Videothek/genre_schau/arnold.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="genre_schau.xslt"?>
<resultset statement="SELECT * FROM filmen WHERE genres LIKE '%Action%' AND schauspieler LIKE '%Arnold Schwarzenegger%' AND jahr &gt; 1990 AND jahr &lt; 2000
" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="genre_schau.xsd">
  <row>
	<field name="id">40</field>
	<field name="titel">Terminator 2: Judgment Day</field>
	<field name="jahr">1991</field>
	<field name="laenge">137 min</field>
	<field name="genres">&quot;Action;Sci-Fi;Thriller&quot;</field>
	<field name="regisseure">&quot;James Cameron&quot;</field>
	<field name="schauspieler">&quot;Arnold Schwarzenegger;Edward Furlong;Linda Hamilton;Robert Patrick&quot;</field>
	<field name="plot">&quot;A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced cyborg.&quot;</field>
	<field name="sprache">&quot;English;Spanish&quot;</field>
	<field name="laender">&quot;France;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BZDM2YjYwYWMtMWZlNi00ZDQxLWExMDctMDAzNzQ0OTkzZjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg</field>
	<field name="imdbID">tt0103064</field>
  </row>
</resultset>

=== JoLuMTavares/Videothek/genre_schau/morganf.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="genre_schau.xslt"?>
<resultset statement="SELECT * FROM filmen WHERE genres LIKE '%Crime%' AND schauspieler LIKE '%Morgan Freeman%' AND jahr &gt; 1990 AND jahr &lt; 2000
" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="genre_schau.xsd">
  <row>
	<field name="id">2</field>
	<field name="titel">The Shawshank Redemption</field>
	<field name="jahr">1994</field>
	<field name="laenge">142 min</field>
	<field name="genres">&quot;Crime;Drama&quot;</field>
	<field name="regisseure">&quot;Frank Darabont&quot;</field>
	<field name="schauspieler">&quot;Bob Gunton;Morgan Freeman;Tim Robbins;William Sadler&quot;</field>
	<field name="plot">&quot;Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.&quot;</field>
	<field name="sprache">&quot;English&quot;</field>
	<field name="laender">&quot;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SX300.jpg</field>
	<field name="imdbID">tt0111161</field>
  </row>

  <row>
	<field name="id">18</field>
	<field name="titel">Se7en</field>
	<field name="jahr">1995</field>
	<field name="laenge">127 min</field>
	<field name="genres">&quot;Crime;Drama;Mystery&quot;</field>
	<field name="regisseure">&quot;David Fincher&quot;</field>
	<field name="schauspieler">&quot;Andrew Kevin Walker;Daniel Zacapa;Kevin Spacey;Morgan Freeman&quot;</field>
	<field name="plot">&quot;Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.&quot;</field>
	<field name="sprache">&quot;English&quot;</field>
	<field name="laender">&quot;USA&quot;</field>
	<field name="plakat_url|">https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg</field>
	<field name="imdbID">tt0114369</field>
  </row>
</resultset>
